### ISSUE TITLE
Make foldMap stack safe

### ISSUE THREAD

**Issue by safareli** [safareli/free#22]
Running this snippet results in `RangeError: Maximum call stack size exceeded`:

``` js
const Identity = require('fantasy-identities')
const Free = require('@safareli/free')
const runTimes = (n) => (v) => {
  console.log(v);
  const res = Free.liftF(n)
  if (n == 0){
    return res
  }
  return res.chain(runTimes(n-1))
}
console.log(runTimes(1000000)().foldMap(Identity,Identity))
```

**Comment by LiamGoodacre** [comment]
I don't know much about it; however after reading both:
- the `purescript-free` implementation (https://github.com/purescript/purescript-free/blob/master/src/Control/Monad/Free.purs#L107)
- the `cats` implementation (https://github.com/typelevel/cats/blob/master/free/src/main/scala/cats/free/Free.scala#L122)

They implement it based on a `MonadRec` instead of a fold (`cata`).

Hope this helps!

**Comment by safareli** [comment]
@LiamGoodacre Thanks! But I have looked looked at them and that `MonadRec` is kinda mysterious for me. I tried to dig into purescript-tailrec but unfortunately there are no so many resources about `MonadRec`

**Comment by safareli** [comment]
@paf31's paper [Stack Safety for Free](https://github.com/functorial/stack-safety-for-free/blob/gh-pages/index.markdown) was pritty helpfull but still a bit hard. even thou I have made an implementation of tailRecM for Task (which was hardest), and here is some WIP [changes](https://github.com/safareli/free/commit/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841).

---

I have also created issue [fantasy-land#151](https://github.com/fantasyland/fantasy-land/issues/151) for adding TailRec type class to fantasy-land.

---

One thing to note is that, using TailRec made Free better in performance.

# Before using `tailRecM`

```
$ node test/examples/list.js
100: 5.707ms
200: 16.894ms
300: 44.943ms
400: 71.038ms
500: 128.910ms
600: 172.079ms
700: 193.591ms
800: 352.388ms
900: 311.828ms
1000: 509.392ms
1100: 474.403ms
1200: 853.587ms
1300: 633.945ms
1400: 1260.444ms
1500: 862.586ms
1600: 1366.490ms
1700: 1046.310ms
1800: 2025.226ms
1900: 1722.003ms
2000: 2646.174ms
2100: 2301.928ms
2200: 2211.718ms
2300: 2265.449ms
2400: 2812.602ms
2500: 3340.075ms
2600: 3827.182ms
2700: 4043.537ms
2800: 5010.874ms
2900: 5032.038ms
3000: 7308.983ms
```

> more than 3000 crashed node process with `Allocation failed - process out of memory`

# After  using `tailRecM`

```
$ node test/examples/list.js
100: 7.407ms
200: 11.254ms
300: 14.572ms
400: 26.952ms
500: 34.157ms
600: 43.095ms
700: 67.985ms
800: 68.443ms
900: 82.214ms
1000: 104.718ms
1100: 121.038ms
1200: 132.095ms
1300: 162.392ms
1400: 168.575ms
1500: 245.622ms
1600: 249.172ms
1700: 302.374ms
1800: 309.117ms
1900: 319.903ms
2000: 364.573ms
2100: 368.800ms
2200: 476.156ms
2300: 474.548ms
2400: 508.497ms
2500: 553.902ms
2600: 598.245ms
2700: 693.121ms
2800: 781.083ms
2900: 781.916ms
3000: 822.924ms
4000: 1467.550ms
5000: 2685.777ms
6000: 3976.970ms
7000: 5740.519ms
8000: 7887.287ms
9000: 9014.637ms
10000: 12283.854ms
11000: 15859.906ms
12000: 19204.177ms
```

**Comment by safareli** [comment]
Now as [fantasy-land/pull/152](https://github.com/fantasyland/fantasy-land/pull/152) is landed I need to create PRs to popular Either, identity, Task/Future implementations to conform ChainRec spec, and then move changes from branch `MonadRec` to dev
