### ISSUE TITLE
is Monkey Patch Function.prototype required?

### ISSUE THREAD

**Issue by syaiful6** [safareli/free#25]
Hi, thanks for this repo @safareli, i am used this repo on my project, and it great so far. To clarify, i am not against the way this library monkey patch the Function prototype, but it just my curiosity, is this required?

**Comment by safareli** [comment]
In #24 I'm waiting [sanctuary-type-classes#2](https://github.com/sanctuary-js/sanctuary-type-classes/pull/2) to be merged and then I would be able to remove that as sanctuary-type-classes will provides Functor interface for Function. Currently it's needed [here](https://github.com/safareli/free/blob/bf397db23fce6b8db1cd4875e6513726005a71e4/src/free.js#L102) and 1 to 1 translation from [haskel vertion](https://github.com/srijs/haskell-free-concurrent/blob/1a56280e8d63e037cf8f9e57aa17ac6a8ac817a5/src/Control/Concurrent/Free.hs#L38)
